eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
microservices:
  payment-service:
    endpoints:
      endpoint:
        uri: http://payment-service/payment-api/doPayment
  order-service:
    endpoints:
      endpoint:
        uri: "http://order-service/order-api/bookOrder"
